services:
  db:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sert
      POSTGRES_PASSWORD: sert
      POSTGRES_DB: sert
      TZ: Asia/Bangkok
    ports:
      - "5438:5432"             # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sert -d sert -h 127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:
